.TH "D:/Longfei/Desktop/catkin_KinovaROS/devel/lib/python2.7/dist-packages/jaco_msgs/msg/_SetFingersPositionFeedback.py" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/devel/lib/python2.7/dist-packages/jaco_msgs/msg/_SetFingersPositionFeedback.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjaco_msgs\&.msg\&._SetFingersPositionFeedback\&.SetFingersPositionFeedback\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjaco_msgs\&.msg\&._SetFingersPositionFeedback\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBjaco_msgs\&.msg\&._SetFingersPositionFeedback\&._struct_3f\fP = struct\&.Struct('<3f')"
.br
.ti -1c
.RI "\fBjaco_msgs\&.msg\&._SetFingersPositionFeedback\&._struct_I\fP = genpy\&.struct_I"
.br
.ti -1c
.RI "bool \fBjaco_msgs\&.msg\&._SetFingersPositionFeedback\&.python3\fP = True"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
