.TH "D:/Longfei/Desktop/catkin_KinovaROS/build/CMakeFiles/CompilerIdC/CMakeCCompilerId.c" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/build/CMakeFiles/CompilerIdC/CMakeCCompilerId.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBARCHITECTURE_ID\fP   ''"
.br
.ti -1c
.RI "#define \fBCOMPILER_ID\fP   ''"
.br
.ti -1c
.RI "#define \fBDEC\fP(n)                                  "
.br
.ti -1c
.RI "#define \fBHEX\fP(n)                      "
.br
.ti -1c
.RI "#define \fBPLATFORM_ID\fP   ''"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char const * \fBinfo_arch\fP = 'INFO' ':' 'arch[' ARCHITECTURE_ID ']'"
.br
.ti -1c
.RI "char const * \fBinfo_compiler\fP = 'INFO' ':' 'compiler[' COMPILER_ID ']'"
.br
.ti -1c
.RI "char const * \fBinfo_platform\fP = 'INFO' ':' 'platform[' PLATFORM_ID ']'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARCHITECTURE_ID   ''"

.SS "#define COMPILER_ID   ''"

.SS "#define DEC(n)"
\fBValue:\fP
.PP
.nf
('0' + (((n) / 10000000)%10)), \
  ('0' + (((n) / 1000000)%10)),  \
  ('0' + (((n) / 100000)%10)),   \
  ('0' + (((n) / 10000)%10)),    \
  ('0' + (((n) / 1000)%10)),     \
  ('0' + (((n) / 100)%10)),      \
  ('0' + (((n) / 10)%10)),       \
  ('0' +  ((n) % 10))
.fi
.SS "#define HEX(n)"
\fBValue:\fP
.PP
.nf
('0' + ((n)>>28 & 0xF)), \
  ('0' + ((n)>>24 & 0xF)), \
  ('0' + ((n)>>20 & 0xF)), \
  ('0' + ((n)>>16 & 0xF)), \
  ('0' + ((n)>>12 & 0xF)), \
  ('0' + ((n)>>8  & 0xF)), \
  ('0' + ((n)>>4  & 0xF)), \
  ('0' + ((n)     & 0xF))
.fi
.SS "#define PLATFORM_ID   ''"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
.nf
350 {
351   int require = 0;
352   require += info_compiler[argc];
353   require += info_platform[argc];
354   require += info_arch[argc];
355 #ifdef COMPILER_VERSION_MAJOR
356   require += info_version[argc];
357 #endif
358   (void)argv;
359   return require;
360 }
.fi
.SH "Variable Documentation"
.PP 
.SS "char const* info_arch = 'INFO' ':' 'arch[' ARCHITECTURE_ID ']'"

.SS "char const* info_compiler = 'INFO' ':' 'compiler[' COMPILER_ID ']'"

.SS "char const* info_platform = 'INFO' ':' 'platform[' PLATFORM_ID ']'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
