.TH "generate_cached_setup" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generate_cached_setup \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcode\fP = generate_environment_script('/home/longfei/catkin_KinovaROS/devel/env\&.sh')"
.br
.ti -1c
.RI "\fBmode\fP = os\&.stat(\fBoutput_filename\fP)\&.st_mode"
.br
.ti -1c
.RI "string \fBoutput_filename\fP = '/home/longfei/catkin_KinovaROS/build/catkin_generated/setup_cached\&.sh'"
.br
.ti -1c
.RI "\fBpython_path\fP = os\&.path\&.join(workspace, 'lib/python2\&.7/dist\-packages')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "generate_cached_setup\&.code = generate_environment_script('/home/longfei/catkin_KinovaROS/devel/env\&.sh')"

.SS "generate_cached_setup\&.mode = os\&.stat(\fBoutput_filename\fP)\&.st_mode"

.SS "string generate_cached_setup\&.output_filename = '/home/longfei/catkin_KinovaROS/build/catkin_generated/setup_cached\&.sh'"

.SS "generate_cached_setup\&.python_path = os\&.path\&.join(workspace, 'lib/python2\&.7/dist\-packages')"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
