.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_demo/nodes/jaco_demo/goal_generators.py" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_demo/nodes/jaco_demo/goal_generators.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgoal_generators\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgoal_generators\&.joint_angles_from_file\fP (filepath)"
.br
.ti -1c
.RI "def \fBgoal_generators\&.poses_from_file\fP (filepath)"
.br
.ti -1c
.RI "def \fBgoal_generators\&.random_jaco_finger_positions\fP (n_positions=1)"
.br
.ti -1c
.RI "def \fBgoal_generators\&.random_joint_angles_generator\fP (n_poses=1)"
.br
.ti -1c
.RI "def \fBgoal_generators\&.random_mico_finger_positions\fP (n_positions=1)"
.br
.ti -1c
.RI "def \fBgoal_generators\&.random_pose_generator\fP (n_poses=1)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgoal_generators\&.n_fingers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
