.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_demo/nodes/jaco_demo/grip_workout.py" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_demo/nodes/jaco_demo/grip_workout.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgrip_workout\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgrip_workout\&.gripper_client\fP (finger_positions)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgrip_workout\&.positions\fP = \fBgoal_generators\&.random_jaco_finger_positions\fP(int(sys\&.argv[3]))"
.br
.ti -1c
.RI "list \fBgrip_workout\&.raw_positions\fP = [float(n) for n in sys\&.argv[2:]]"
.br
.ti -1c
.RI "\fBgrip_workout\&.result\fP = gripper_client(position)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
