.TH "jaco_msgs::FingerPosition_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::FingerPosition_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'FingerPosition\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef float \fB_finger1_type\fP"
.br
.ti -1c
.RI "typedef float \fB_finger2_type\fP"
.br
.ti -1c
.RI "typedef float \fB_finger3_type\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::FingerPosition_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::FingerPosition_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBFingerPosition_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFingerPosition_\fP ()"
.br
.ti -1c
.RI "\fBFingerPosition_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.ti -1c
.RI "\fB_finger1_type\fP \fBfinger1\fP"
.br
.ti -1c
.RI "\fB_finger2_type\fP \fBfinger2\fP"
.br
.ti -1c
.RI "\fB_finger3_type\fP \fBfinger3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::FingerPosition_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef float \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::\fB_finger1_type\fP"

.SS "template<class ContainerAllocator> typedef float \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::\fB_finger2_type\fP"

.SS "template<class ContainerAllocator> typedef float \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::\fB_finger3_type\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::FingerPosition_\fP<ContainerAllocator> const> \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::FingerPosition_\fP<ContainerAllocator> > \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBFingerPosition_\fP<ContainerAllocator> \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::\fBFingerPosition_\fP ()\fC [inline]\fP"

.PP
.nf
60     : finger1(0\&.0)
61     , finger2(0\&.0)
62     , finger3(0\&.0)  {
63     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::\fBFingerPosition_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
65     : finger1(0\&.0)
66     , finger2(0\&.0)
67     , finger3(0\&.0)  {
68     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::__connection_header"

.SS "template<class ContainerAllocator> \fB_finger1_type\fP \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::finger1"

.SS "template<class ContainerAllocator> \fB_finger2_type\fP \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::finger2"

.SS "template<class ContainerAllocator> \fB_finger3_type\fP \fBjaco_msgs::FingerPosition_\fP< ContainerAllocator >::finger3"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
