.TH "jaco_msgs::ArmPoseActionResult_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::ArmPoseActionResult_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'ArmPoseActionResult\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ::std_msgs::Header_< ContainerAllocator > \fB_header_type\fP"
.br
.ti -1c
.RI "typedef ::\fBjaco_msgs::ArmPoseResult_\fP< ContainerAllocator > \fB_result_type\fP"
.br
.ti -1c
.RI "typedef ::actionlib_msgs::GoalStatus_< ContainerAllocator > \fB_status_type\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBArmPoseActionResult_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArmPoseActionResult_\fP ()"
.br
.ti -1c
.RI "\fBArmPoseActionResult_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.ti -1c
.RI "\fB_header_type\fP \fBheader\fP"
.br
.ti -1c
.RI "\fB_result_type\fP \fBresult\fP"
.br
.ti -1c
.RI "\fB_status_type\fP \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::ArmPoseActionResult_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef ::std_msgs::Header_<ContainerAllocator> \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::\fB_header_type\fP"

.SS "template<class ContainerAllocator> typedef ::\fBjaco_msgs::ArmPoseResult_\fP<ContainerAllocator> \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::\fB_result_type\fP"

.SS "template<class ContainerAllocator> typedef ::actionlib_msgs::GoalStatus_<ContainerAllocator> \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::\fB_status_type\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseActionResult_\fP<ContainerAllocator> const> \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseActionResult_\fP<ContainerAllocator> > \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBArmPoseActionResult_\fP<ContainerAllocator> \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::\fBArmPoseActionResult_\fP ()\fC [inline]\fP"

.PP
.nf
63     : header()
64     , status()
65     , result()  {
66     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::\fBArmPoseActionResult_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
68     : header(_alloc)
69     , status(_alloc)
70     , result(_alloc)  {
71     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::__connection_header"

.SS "template<class ContainerAllocator> \fB_header_type\fP \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::header"

.SS "template<class ContainerAllocator> \fB_result_type\fP \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::result"

.SS "template<class ContainerAllocator> \fB_status_type\fP \fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator >::status"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
