.TH "jaco_msgs::JointAngles_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::JointAngles_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'JointAngles\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef float \fB_joint1_type\fP"
.br
.ti -1c
.RI "typedef float \fB_joint2_type\fP"
.br
.ti -1c
.RI "typedef float \fB_joint3_type\fP"
.br
.ti -1c
.RI "typedef float \fB_joint4_type\fP"
.br
.ti -1c
.RI "typedef float \fB_joint5_type\fP"
.br
.ti -1c
.RI "typedef float \fB_joint6_type\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::JointAngles_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::JointAngles_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBJointAngles_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJointAngles_\fP ()"
.br
.ti -1c
.RI "\fBJointAngles_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.ti -1c
.RI "\fB_joint1_type\fP \fBjoint1\fP"
.br
.ti -1c
.RI "\fB_joint2_type\fP \fBjoint2\fP"
.br
.ti -1c
.RI "\fB_joint3_type\fP \fBjoint3\fP"
.br
.ti -1c
.RI "\fB_joint4_type\fP \fBjoint4\fP"
.br
.ti -1c
.RI "\fB_joint5_type\fP \fBjoint5\fP"
.br
.ti -1c
.RI "\fB_joint6_type\fP \fBjoint6\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::JointAngles_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef float \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fB_joint1_type\fP"

.SS "template<class ContainerAllocator> typedef float \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fB_joint2_type\fP"

.SS "template<class ContainerAllocator> typedef float \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fB_joint3_type\fP"

.SS "template<class ContainerAllocator> typedef float \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fB_joint4_type\fP"

.SS "template<class ContainerAllocator> typedef float \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fB_joint5_type\fP"

.SS "template<class ContainerAllocator> typedef float \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fB_joint6_type\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::JointAngles_\fP<ContainerAllocator> const> \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::JointAngles_\fP<ContainerAllocator> > \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBJointAngles_\fP<ContainerAllocator> \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fBJointAngles_\fP ()\fC [inline]\fP"

.PP
.nf
60     : joint1(0\&.0)
61     , joint2(0\&.0)
62     , joint3(0\&.0)
63     , joint4(0\&.0)
64     , joint5(0\&.0)
65     , joint6(0\&.0)  {
66     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::\fBJointAngles_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
68     : joint1(0\&.0)
69     , joint2(0\&.0)
70     , joint3(0\&.0)
71     , joint4(0\&.0)
72     , joint5(0\&.0)
73     , joint6(0\&.0)  {
74     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::__connection_header"

.SS "template<class ContainerAllocator> \fB_joint1_type\fP \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::joint1"

.SS "template<class ContainerAllocator> \fB_joint2_type\fP \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::joint2"

.SS "template<class ContainerAllocator> \fB_joint3_type\fP \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::joint3"

.SS "template<class ContainerAllocator> \fB_joint4_type\fP \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::joint4"

.SS "template<class ContainerAllocator> \fB_joint5_type\fP \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::joint5"

.SS "template<class ContainerAllocator> \fB_joint6_type\fP \fBjaco_msgs::JointAngles_\fP< ContainerAllocator >::joint6"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
