.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/include/jaco_driver/jaco_types.h" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/include/jaco_driver/jaco_types.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <kinova/KinovaTypes\&.h>\fP
.br
\fC#include <geometry_msgs/Pose\&.h>\fP
.br
\fC#include <geometry_msgs/Wrench\&.h>\fP
.br
\fC#include <jaco_msgs/JointAngles\&.h>\fP
.br
\fC#include <jaco_msgs/FingerPosition\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjaco::FingerAngles\fP"
.br
.ti -1c
.RI "class \fBjaco::JacoAngles\fP"
.br
.ti -1c
.RI "class \fBjaco::JacoCommException\fP"
.br
.ti -1c
.RI "class \fBjaco::JacoException\fP"
.br
.ti -1c
.RI "class \fBjaco::JacoPose\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjaco\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
