.TH "jaco_msgs::StartResponse_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::StartResponse_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'StartResponse\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::basic_string< char, std::char_traits< char >, typename ContainerAllocator::template rebind< char >::other > \fB_start_result_type\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::StartResponse_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::StartResponse_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBStartResponse_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStartResponse_\fP ()"
.br
.ti -1c
.RI "\fBStartResponse_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.ti -1c
.RI "\fB_start_result_type\fP \fBstart_result\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::StartResponse_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > \fBjaco_msgs::StartResponse_\fP< ContainerAllocator >::\fB_start_result_type\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::StartResponse_\fP<ContainerAllocator> const> \fBjaco_msgs::StartResponse_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::StartResponse_\fP<ContainerAllocator> > \fBjaco_msgs::StartResponse_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBStartResponse_\fP<ContainerAllocator> \fBjaco_msgs::StartResponse_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::StartResponse_\fP< ContainerAllocator >::\fBStartResponse_\fP ()\fC [inline]\fP"

.PP
.nf
60     : start_result()  {
61     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::StartResponse_\fP< ContainerAllocator >::\fBStartResponse_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
63     : start_result(_alloc)  {
64     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::StartResponse_\fP< ContainerAllocator >::__connection_header"

.SS "template<class ContainerAllocator> \fB_start_result_type\fP \fBjaco_msgs::StartResponse_\fP< ContainerAllocator >::start_result"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
