.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/include/jaco_driver/jaco_arm.h" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/include/jaco_driver/jaco_arm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <geometry_msgs/PoseStamped\&.h>\fP
.br
\fC#include <geometry_msgs/WrenchStamped\&.h>\fP
.br
\fC#include <geometry_msgs/TwistStamped\&.h>\fP
.br
\fC#include <tf/tf\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include <sensor_msgs/JointState\&.h>\fP
.br
\fC#include <jaco_msgs/Stop\&.h>\fP
.br
\fC#include <jaco_msgs/Start\&.h>\fP
.br
\fC#include <jaco_msgs/HomeArm\&.h>\fP
.br
\fC#include <jaco_msgs/JointVelocity\&.h>\fP
.br
\fC#include <jaco_msgs/FingerPosition\&.h>\fP
.br
\fC#include <jaco_msgs/JointAngles\&.h>\fP
.br
\fC#include <jaco_msgs/SetForceControlParams\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'kinova/KinovaTypes\&.h'\fP
.br
\fC#include 'jaco_driver/jaco_comm\&.h'\fP
.br
\fC#include 'jaco_driver/jaco_api\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjaco::JacoArm\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjaco\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBjaco::JACO_JOINTS_COUNT\fP = 9"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
