.TH "jaco_msgs::SetFingersPositionActionGoal_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::SetFingersPositionActionGoal_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'SetFingersPositionActionGoal\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ::actionlib_msgs::GoalID_< ContainerAllocator > \fB_goal_id_type\fP"
.br
.ti -1c
.RI "typedef ::\fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator > \fB_goal_type\fP"
.br
.ti -1c
.RI "typedef ::std_msgs::Header_< ContainerAllocator > \fB_header_type\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBSetFingersPositionActionGoal_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetFingersPositionActionGoal_\fP ()"
.br
.ti -1c
.RI "\fBSetFingersPositionActionGoal_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.ti -1c
.RI "\fB_goal_type\fP \fBgoal\fP"
.br
.ti -1c
.RI "\fB_goal_id_type\fP \fBgoal_id\fP"
.br
.ti -1c
.RI "\fB_header_type\fP \fBheader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::SetFingersPositionActionGoal_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef ::actionlib_msgs::GoalID_<ContainerAllocator> \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::\fB_goal_id_type\fP"

.SS "template<class ContainerAllocator> typedef ::\fBjaco_msgs::SetFingersPositionGoal_\fP<ContainerAllocator> \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::\fB_goal_type\fP"

.SS "template<class ContainerAllocator> typedef ::std_msgs::Header_<ContainerAllocator> \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::\fB_header_type\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::SetFingersPositionActionGoal_\fP<ContainerAllocator> const> \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::SetFingersPositionActionGoal_\fP<ContainerAllocator> > \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBSetFingersPositionActionGoal_\fP<ContainerAllocator> \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::\fBSetFingersPositionActionGoal_\fP ()\fC [inline]\fP"

.PP
.nf
63     : header()
64     , goal_id()
65     , goal()  {
66     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::\fBSetFingersPositionActionGoal_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
68     : header(_alloc)
69     , goal_id(_alloc)
70     , goal(_alloc)  {
71     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::__connection_header"

.SS "template<class ContainerAllocator> \fB_goal_type\fP \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::goal"

.SS "template<class ContainerAllocator> \fB_goal_id_type\fP \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::goal_id"

.SS "template<class ContainerAllocator> \fB_header_type\fP \fBjaco_msgs::SetFingersPositionActionGoal_\fP< ContainerAllocator >::header"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
