.TH "jaco_msgs::SetFingersPositionGoal_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::SetFingersPositionGoal_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'SetFingersPositionGoal\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ::\fBjaco_msgs::FingerPosition_\fP< ContainerAllocator > \fB_fingers_type\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBSetFingersPositionGoal_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetFingersPositionGoal_\fP ()"
.br
.ti -1c
.RI "\fBSetFingersPositionGoal_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.ti -1c
.RI "\fB_fingers_type\fP \fBfingers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::SetFingersPositionGoal_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef ::\fBjaco_msgs::FingerPosition_\fP<ContainerAllocator> \fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator >::\fB_fingers_type\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::SetFingersPositionGoal_\fP<ContainerAllocator> const> \fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::SetFingersPositionGoal_\fP<ContainerAllocator> > \fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBSetFingersPositionGoal_\fP<ContainerAllocator> \fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator >::\fBSetFingersPositionGoal_\fP ()\fC [inline]\fP"

.PP
.nf
61     : fingers()  {
62     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator >::\fBSetFingersPositionGoal_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
64     : fingers(_alloc)  {
65     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator >::__connection_header"

.SS "template<class ContainerAllocator> \fB_fingers_type\fP \fBjaco_msgs::SetFingersPositionGoal_\fP< ContainerAllocator >::fingers"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
