.TH "jaco_msgs.srv._Stop.Stop" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs.srv._Stop.Stop \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "string \fB_md5sum\fP = '585dc4164508d473dff8f8b67a05d2ad'"
.br
.ti -1c
.RI "\fB_request_class\fP = \fBStopRequest\fP"
.br
.ti -1c
.RI "\fB_response_class\fP = \fBStopResponse\fP"
.br
.ti -1c
.RI "string \fB_type\fP = 'jaco_msgs/\fBStop\fP'"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Member Data Documentation"
.PP 
.SS "string jaco_msgs\&.srv\&._Stop\&.Stop\&._md5sum = '585dc4164508d473dff8f8b67a05d2ad'\fC [static]\fP, \fC [private]\fP"

.SS "jaco_msgs\&.srv\&._Stop\&.Stop\&._request_class = \fBStopRequest\fP\fC [static]\fP, \fC [private]\fP"

.SS "jaco_msgs\&.srv\&._Stop\&.Stop\&._response_class = \fBStopResponse\fP\fC [static]\fP, \fC [private]\fP"

.SS "string jaco_msgs\&.srv\&._Stop\&.Stop\&._type = 'jaco_msgs/\fBStop\fP'\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
