.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/src/jaco_types.cpp" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/src/jaco_types.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <angles/angles\&.h>\fP
.br
\fC#include <tf/tf\&.h>\fP
.br
\fC#include <jaco_driver/jaco_types\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjaco\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBjaco::areValuesClose\fP (float first, float second, float tolerance)"
.br
.ti -1c
.RI "float \fBjaco::normalizeInDegrees\fP (float degrees)"
.br
.ti -1c
.RI "float \fBjaco::normalizeInRads\fP (float rads)"
.br
.ti -1c
.RI "float \fBjaco::normalizePositiveInDegrees\fP (float degrees)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
