.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/include/jaco_driver/jaco_api.h" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/include/jaco_driver/jaco_api.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dlfcn\&.h>\fP
.br
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'kinova/Kinova\&.API\&.UsbCommandLayerUbuntu\&.h'\fP
.br
\fC#include 'kinova/KinovaTypes\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjaco::JacoAPI\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjaco\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBJACO_USB_LIBRARY\fP   'Kinova\&.API\&.USBCommandLayerUbuntu\&.so'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define JACO_USB_LIBRARY   'Kinova\&.API\&.USBCommandLayerUbuntu\&.so'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
