.TH "jaco_msgs::ArmPoseAction_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::ArmPoseAction_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'ArmPoseAction\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ::\fBjaco_msgs::ArmPoseActionFeedback_\fP< ContainerAllocator > \fB_action_feedback_type\fP"
.br
.ti -1c
.RI "typedef ::\fBjaco_msgs::ArmPoseActionGoal_\fP< ContainerAllocator > \fB_action_goal_type\fP"
.br
.ti -1c
.RI "typedef ::\fBjaco_msgs::ArmPoseActionResult_\fP< ContainerAllocator > \fB_action_result_type\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBArmPoseAction_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArmPoseAction_\fP ()"
.br
.ti -1c
.RI "\fBArmPoseAction_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.ti -1c
.RI "\fB_action_feedback_type\fP \fBaction_feedback\fP"
.br
.ti -1c
.RI "\fB_action_goal_type\fP \fBaction_goal\fP"
.br
.ti -1c
.RI "\fB_action_result_type\fP \fBaction_result\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::ArmPoseAction_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef ::\fBjaco_msgs::ArmPoseActionFeedback_\fP<ContainerAllocator> \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::\fB_action_feedback_type\fP"

.SS "template<class ContainerAllocator> typedef ::\fBjaco_msgs::ArmPoseActionGoal_\fP<ContainerAllocator> \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::\fB_action_goal_type\fP"

.SS "template<class ContainerAllocator> typedef ::\fBjaco_msgs::ArmPoseActionResult_\fP<ContainerAllocator> \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::\fB_action_result_type\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseAction_\fP<ContainerAllocator> const> \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseAction_\fP<ContainerAllocator> > \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBArmPoseAction_\fP<ContainerAllocator> \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::\fBArmPoseAction_\fP ()\fC [inline]\fP"

.PP
.nf
63     : action_goal()
64     , action_result()
65     , action_feedback()  {
66     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::\fBArmPoseAction_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
68     : action_goal(_alloc)
69     , action_result(_alloc)
70     , action_feedback(_alloc)  {
71     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::__connection_header"

.SS "template<class ContainerAllocator> \fB_action_feedback_type\fP \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::action_feedback"

.SS "template<class ContainerAllocator> \fB_action_goal_type\fP \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::action_goal"

.SS "template<class ContainerAllocator> \fB_action_result_type\fP \fBjaco_msgs::ArmPoseAction_\fP< ContainerAllocator >::action_result"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
