.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/src/jaco_arm.cpp" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/src/jaco_arm.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'jaco_driver/jaco_arm\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBanonymous_namespace{jaco_arm\&.cpp}\fP"
.br
.ti -1c
.RI " \fBjaco\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3\&.14159265359"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBanonymous_namespace{jaco_arm\&.cpp}::convertKinDeg\fP (double &qd)"
.br
.RI "\fIConvert Kinova-specific angle degree variations (0\&.\&.180, 360-181) to a more regular representation (0\&.\&.180, -180\&.\&.0)\&. \fP"
.ti -1c
.RI "void \fBanonymous_namespace{jaco_arm\&.cpp}::convertKinDeg\fP (std::vector< double > &qds)"
.br
.ti -1c
.RI "void \fBanonymous_namespace{jaco_arm\&.cpp}::convertKinDeg\fP (geometry_msgs::Vector3 &qds)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PI   3\&.14159265359"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
