.TH "jaco_msgs::SetForceControlParamsRequest_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::SetForceControlParamsRequest_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'SetForceControlParamsRequest\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ::geometry_msgs::Vector3_< ContainerAllocator > \fB_damping_angular_type\fP"
.br
.ti -1c
.RI "typedef ::geometry_msgs::Vector3_< ContainerAllocator > \fB_damping_linear_type\fP"
.br
.ti -1c
.RI "typedef ::geometry_msgs::Vector3_< ContainerAllocator > \fB_force_max_angular_type\fP"
.br
.ti -1c
.RI "typedef ::geometry_msgs::Vector3_< ContainerAllocator > \fB_force_max_linear_type\fP"
.br
.ti -1c
.RI "typedef ::geometry_msgs::Vector3_< ContainerAllocator > \fB_force_min_angular_type\fP"
.br
.ti -1c
.RI "typedef ::geometry_msgs::Vector3_< ContainerAllocator > \fB_force_min_linear_type\fP"
.br
.ti -1c
.RI "typedef ::geometry_msgs::Vector3_< ContainerAllocator > \fB_inertia_angular_type\fP"
.br
.ti -1c
.RI "typedef ::geometry_msgs::Vector3_< ContainerAllocator > \fB_inertia_linear_type\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBSetForceControlParamsRequest_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetForceControlParamsRequest_\fP ()"
.br
.ti -1c
.RI "\fBSetForceControlParamsRequest_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.ti -1c
.RI "\fB_damping_angular_type\fP \fBdamping_angular\fP"
.br
.ti -1c
.RI "\fB_damping_linear_type\fP \fBdamping_linear\fP"
.br
.ti -1c
.RI "\fB_force_max_angular_type\fP \fBforce_max_angular\fP"
.br
.ti -1c
.RI "\fB_force_max_linear_type\fP \fBforce_max_linear\fP"
.br
.ti -1c
.RI "\fB_force_min_angular_type\fP \fBforce_min_angular\fP"
.br
.ti -1c
.RI "\fB_force_min_linear_type\fP \fBforce_min_linear\fP"
.br
.ti -1c
.RI "\fB_inertia_angular_type\fP \fBinertia_angular\fP"
.br
.ti -1c
.RI "\fB_inertia_linear_type\fP \fBinertia_linear\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::SetForceControlParamsRequest_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef ::geometry_msgs::Vector3_<ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fB_damping_angular_type\fP"

.SS "template<class ContainerAllocator> typedef ::geometry_msgs::Vector3_<ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fB_damping_linear_type\fP"

.SS "template<class ContainerAllocator> typedef ::geometry_msgs::Vector3_<ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fB_force_max_angular_type\fP"

.SS "template<class ContainerAllocator> typedef ::geometry_msgs::Vector3_<ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fB_force_max_linear_type\fP"

.SS "template<class ContainerAllocator> typedef ::geometry_msgs::Vector3_<ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fB_force_min_angular_type\fP"

.SS "template<class ContainerAllocator> typedef ::geometry_msgs::Vector3_<ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fB_force_min_linear_type\fP"

.SS "template<class ContainerAllocator> typedef ::geometry_msgs::Vector3_<ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fB_inertia_angular_type\fP"

.SS "template<class ContainerAllocator> typedef ::geometry_msgs::Vector3_<ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fB_inertia_linear_type\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::SetForceControlParamsRequest_\fP<ContainerAllocator> const> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::SetForceControlParamsRequest_\fP<ContainerAllocator> > \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBSetForceControlParamsRequest_\fP<ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fBSetForceControlParamsRequest_\fP ()\fC [inline]\fP"

.PP
.nf
68     : inertia_linear()
69     , inertia_angular()
70     , damping_linear()
71     , damping_angular()
72     , force_min_linear()
73     , force_min_angular()
74     , force_max_linear()
75     , force_max_angular()  {
76     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::\fBSetForceControlParamsRequest_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
78     : inertia_linear(_alloc)
79     , inertia_angular(_alloc)
80     , damping_linear(_alloc)
81     , damping_angular(_alloc)
82     , force_min_linear(_alloc)
83     , force_min_angular(_alloc)
84     , force_max_linear(_alloc)
85     , force_max_angular(_alloc)  {
86     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::__connection_header"

.SS "template<class ContainerAllocator> \fB_damping_angular_type\fP \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::damping_angular"

.SS "template<class ContainerAllocator> \fB_damping_linear_type\fP \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::damping_linear"

.SS "template<class ContainerAllocator> \fB_force_max_angular_type\fP \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::force_max_angular"

.SS "template<class ContainerAllocator> \fB_force_max_linear_type\fP \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::force_max_linear"

.SS "template<class ContainerAllocator> \fB_force_min_angular_type\fP \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::force_min_angular"

.SS "template<class ContainerAllocator> \fB_force_min_linear_type\fP \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::force_min_linear"

.SS "template<class ContainerAllocator> \fB_inertia_angular_type\fP \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::inertia_angular"

.SS "template<class ContainerAllocator> \fB_inertia_linear_type\fP \fBjaco_msgs::SetForceControlParamsRequest_\fP< ContainerAllocator >::inertia_linear"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
