.TH "jaco_msgs::StopRequest_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::StopRequest_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'StopRequest\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::StopRequest_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::StopRequest_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBStopRequest_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStopRequest_\fP ()"
.br
.ti -1c
.RI "\fBStopRequest_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::StopRequest_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::StopRequest_\fP<ContainerAllocator> const> \fBjaco_msgs::StopRequest_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::StopRequest_\fP<ContainerAllocator> > \fBjaco_msgs::StopRequest_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBStopRequest_\fP<ContainerAllocator> \fBjaco_msgs::StopRequest_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::StopRequest_\fP< ContainerAllocator >::\fBStopRequest_\fP ()\fC [inline]\fP"

.PP
.nf
60     {
61     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::StopRequest_\fP< ContainerAllocator >::\fBStopRequest_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
63     {
64     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::StopRequest_\fP< ContainerAllocator >::__connection_header"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
