.TH "jaco_msgs::ArmPoseGoal_< ContainerAllocator >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jaco_msgs::ArmPoseGoal_< ContainerAllocator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'ArmPoseGoal\&.h'\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ::geometry_msgs::PoseStamped_< ContainerAllocator > \fB_pose_type\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator > const  > \fBConstPtr\fP"
.br
.ti -1c
.RI "typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator > > \fBPtr\fP"
.br
.ti -1c
.RI "typedef \fBArmPoseGoal_\fP< ContainerAllocator > \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArmPoseGoal_\fP ()"
.br
.ti -1c
.RI "\fBArmPoseGoal_\fP (const ContainerAllocator &_alloc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::shared_ptr< std::map< std::string, std::string > > \fB__connection_header\fP"
.br
.ti -1c
.RI "\fB_pose_type\fP \fBpose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct jaco_msgs::ArmPoseGoal_< ContainerAllocator >"

.SH "Member Typedef Documentation"
.PP 
.SS "template<class ContainerAllocator> typedef ::geometry_msgs::PoseStamped_<ContainerAllocator> \fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator >::\fB_pose_type\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseGoal_\fP<ContainerAllocator> const> \fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator >::\fBConstPtr\fP"

.SS "template<class ContainerAllocator> typedef boost::shared_ptr< ::\fBjaco_msgs::ArmPoseGoal_\fP<ContainerAllocator> > \fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator >::\fBPtr\fP"

.SS "template<class ContainerAllocator> typedef \fBArmPoseGoal_\fP<ContainerAllocator> \fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator >::\fBType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ContainerAllocator> \fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator >::\fBArmPoseGoal_\fP ()\fC [inline]\fP"

.PP
.nf
61     : pose()  {
62     }
.fi
.SS "template<class ContainerAllocator> \fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator >::\fBArmPoseGoal_\fP (const ContainerAllocator & _alloc)\fC [inline]\fP"

.PP
.nf
64     : pose(_alloc)  {
65     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator> boost::shared_ptr<std::map<std::string, std::string> > \fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator >::__connection_header"

.SS "template<class ContainerAllocator> \fB_pose_type\fP \fBjaco_msgs::ArmPoseGoal_\fP< ContainerAllocator >::pose"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
