.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/src/nodes/jaco_tf_updater.cpp" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_driver/src/nodes/jaco_tf_updater.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <jaco_driver/jaco_tf_updater\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjaco\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
.nf
72 {
73     /* Set up ROS */
74     ros::init(argc, argv, "jaco_tf_updater");
75     ros::NodeHandle nh("~");
76 
77     jaco::JacoTFTree JacoTF(nh);
78     ros::spin();
79 
80     return 0;
81 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
