.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_demo/nodes/jaco_demo/joint_angle_workout.py" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_demo/nodes/jaco_demo/joint_angle_workout.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjoint_angle_workout\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBjoint_angle_workout\&.joint_angle_client\fP (angle_set)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBjoint_angle_workout\&.angles\fP = \fBgoal_generators\&.random_joint_angles_generator\fP(int(sys\&.argv[3]))"
.br
.ti -1c
.RI "list \fBjoint_angle_workout\&.raw_angles\fP = [float(n) for n in sys\&.argv[2:]]"
.br
.ti -1c
.RI "\fBjoint_angle_workout\&.result\fP = joint_angle_client(angle_set)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
