.TH "D:/Longfei/Desktop/catkin_KinovaROS/build/catkin_generated/order_packages.py" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/build/catkin_generated/order_packages.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBorder_packages\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBorder_packages\&.blacklisted_packages\fP = ''"
.br
.ti -1c
.RI "string \fBorder_packages\&.source_root_dir\fP = '/home/longfei/catkin_KinovaROS/src'"
.br
.ti -1c
.RI "string \fBorder_packages\&.underlay_workspaces\fP = '/home/longfei/catkin_ws/devel;/opt/ros/hydro'"
.br
.ti -1c
.RI "string \fBorder_packages\&.whitelisted_packages\fP = ''"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
