.TH "order_packages" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
order_packages \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBblacklisted_packages\fP = ''"
.br
.ti -1c
.RI "string \fBsource_root_dir\fP = '/home/longfei/catkin_KinovaROS/src'"
.br
.ti -1c
.RI "string \fBunderlay_workspaces\fP = '/home/longfei/catkin_ws/devel;/opt/ros/hydro'"
.br
.ti -1c
.RI "string \fBwhitelisted_packages\fP = ''"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string order_packages\&.blacklisted_packages = ''"

.SS "string order_packages\&.source_root_dir = '/home/longfei/catkin_KinovaROS/src'"

.SS "string order_packages\&.underlay_workspaces = '/home/longfei/catkin_ws/devel;/opt/ros/hydro'"

.SS "string order_packages\&.whitelisted_packages = ''"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
