.TH "pkg" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pkg \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBCATKIN_PACKAGE_PREFIX\fP = ''"
.br
.ti -1c
.RI "string \fBPKG_CONFIG_LIBRARIES_WITH_PREFIX\fP = ''"
.br
.ti -1c
.RI "string \fBPROJECT_CATKIN_DEPENDS\fP = 'jaco_driver;jaco_msgs;roscpp;rospy;std_msgs;geometry_msgs'"
.br
.ti -1c
.RI "string \fBPROJECT_NAME\fP = 'jaco_demo'"
.br
.ti -1c
.RI "string \fBPROJECT_PKG_CONFIG_INCLUDE_DIRS\fP = ''"
.br
.ti -1c
.RI "string \fBPROJECT_SPACE_DIR\fP = '/home/longfei/catkin_KinovaROS/devel'"
.br
.ti -1c
.RI "string \fBPROJECT_VERSION\fP = '0\&.0\&.1'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string pkg\&.CATKIN_PACKAGE_PREFIX = ''"

.SS "string pkg\&.PKG_CONFIG_LIBRARIES_WITH_PREFIX = ''"

.SS "string pkg\&.PROJECT_CATKIN_DEPENDS = 'jaco_driver;jaco_msgs;roscpp;rospy;std_msgs;geometry_msgs'"

.SS "string pkg\&.PROJECT_NAME = 'jaco_demo'"

.SS "string pkg\&.PROJECT_PKG_CONFIG_INCLUDE_DIRS = ''"

.SS "string pkg\&.PROJECT_SPACE_DIR = '/home/longfei/catkin_KinovaROS/devel'"

.SS "string pkg\&.PROJECT_VERSION = '0\&.0\&.1'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
