.TH "ros::message_operations::Printer< ::jaco_msgs::ArmJointAnglesActionGoal_< ContainerAllocator > >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ros::message_operations::Printer< ::jaco_msgs::ArmJointAnglesActionGoal_< ContainerAllocator > > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'ArmJointAnglesActionGoal\&.h'\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream > static void \fBstream\fP (Stream &s, const std::string &indent, const ::\fBjaco_msgs::ArmJointAnglesActionGoal_\fP< ContainerAllocator > &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct ros::message_operations::Printer< ::jaco_msgs::ArmJointAnglesActionGoal_< ContainerAllocator > >"

.SH "Member Function Documentation"
.PP 
.SS "template<class ContainerAllocator > template<typename Stream > static void ros::message_operations::Printer< ::\fBjaco_msgs::ArmJointAnglesActionGoal_\fP< ContainerAllocator > >::stream (Stream & s, const std::string & indent, const ::\fBjaco_msgs::ArmJointAnglesActionGoal_\fP< ContainerAllocator > & v)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
275   {
276     s << indent << "header: ";
277     s << std::endl;
278     Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v\&.header);
279     s << indent << "goal_id: ";
280     s << std::endl;
281     Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v\&.goal_id);
282     s << indent << "goal: ";
283     s << std::endl;
284     Printer< ::jaco_msgs::ArmJointAnglesGoal_<ContainerAllocator> >::stream(s, indent + "  ", v\&.goal);
285   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
