.TH "ros::serialization::Serializer< ::jaco_msgs::ArmJointAnglesActionGoal_< ContainerAllocator > >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ros::serialization::Serializer< ::jaco_msgs::ArmJointAnglesActionGoal_< ContainerAllocator > > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'ArmJointAnglesActionGoal\&.h'\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream , typename T > static void \fBallInOne\fP (Stream &stream, T m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBROS_DECLARE_ALLINONE_SERIALIZER\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct ros::serialization::Serializer< ::jaco_msgs::ArmJointAnglesActionGoal_< ContainerAllocator > >"

.SH "Member Function Documentation"
.PP 
.SS "template<class ContainerAllocator > template<typename Stream , typename T > static void ros::serialization::Serializer< ::\fBjaco_msgs::ArmJointAnglesActionGoal_\fP< ContainerAllocator > >::allInOne (Stream & stream, T m)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
254     {
255       stream\&.next(m\&.header);
256       stream\&.next(m\&.goal_id);
257       stream\&.next(m\&.goal);
258     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class ContainerAllocator > ros::serialization::Serializer< ::\fBjaco_msgs::ArmJointAnglesActionGoal_\fP< ContainerAllocator > >::ROS_DECLARE_ALLINONE_SERIALIZER"


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
