.TH "ros::service_traits::DataType< ::jaco_msgs::StartRequest >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ros::service_traits::DataType< ::jaco_msgs::StartRequest > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'Start\&.h'\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBvalue\fP ()"
.br
.ti -1c
.RI "static const char * \fBvalue\fP (const ::\fBjaco_msgs::StartRequest\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct ros::service_traits::DataType< ::jaco_msgs::StartRequest >"

.SH "Member Function Documentation"
.PP 
.SS "static const char* ros::service_traits::DataType< ::\fBjaco_msgs::StartRequest\fP >::value ()\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
114   {
115     return DataType< ::jaco_msgs::Start >::value();
116   }
.fi
.SS "static const char* ros::service_traits::DataType< ::\fBjaco_msgs::StartRequest\fP >::value (const ::\fBjaco_msgs::StartRequest\fP &)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
118   {
119     return value();
120   }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
