.TH "ros::message_traits::DataType< ::jaco_msgs::StopResponse_< ContainerAllocator > >" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ros::message_traits::DataType< ::jaco_msgs::StopResponse_< ContainerAllocator > > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'StopResponse\&.h'\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBvalue\fP ()"
.br
.ti -1c
.RI "static const char * \fBvalue\fP (const ::\fBjaco_msgs::StopResponse_\fP< ContainerAllocator > &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ContainerAllocator>
.br
struct ros::message_traits::DataType< ::jaco_msgs::StopResponse_< ContainerAllocator > >"

.SH "Member Function Documentation"
.PP 
.SS "template<class ContainerAllocator > static const char* ros::message_traits::DataType< ::\fBjaco_msgs::StopResponse_\fP< ContainerAllocator > >::value ()\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
161   {
162     return "jaco_msgs/StopResponse";
163   }
.fi
.SS "template<class ContainerAllocator > static const char* ros::message_traits::DataType< ::\fBjaco_msgs::StopResponse_\fP< ContainerAllocator > >::value (const ::\fBjaco_msgs::StopResponse_\fP< ContainerAllocator > &)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
165 { return value(); }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
