.TH "D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_demo/setup.py" 3 "Thu Mar 3 2016" "Version 1.0.1" "Kinova-ROS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Longfei/Desktop/catkin_KinovaROS/src/jaco-ros/jaco_demo/setup.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsetup\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsetup\&.setup_args\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kinova-ROS from the source code\&.
